apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

bases:
- ../../base

resources:
  - namespace.yaml
commonLabels:
  environment: prod
  sre-team: red

patchesStrategicMerge:

- crud-app-replicas.yaml
- crud-ingress.yaml


generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
- name: mysql
  type: Opaque
  behavior: replace
  literals:
  - database=crud
  - user=produser
  - password=prodpass
  - root-password=produserpass
  - server=mysql
