apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
namespace: dev
commonLabels:
  environment: dev
  sre-team: green

patchesStrategicMerge:
- namespace.yaml
- crud-replicas.yaml
- crud-ingress.yaml

secretGenerator:
- name: mysql
  type: Opaque
  literals:
  - database=crud-dev
  - user=devuser
  - password=devpass
  - root-password=devrootpass
  - server=mysql
