apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- ../../base
- namespace.yaml
- crud-apps-dev-certificate.yaml

patches:
- path: crud-app-replicas.yaml
  target:
    kind: Deployment
- path: crud-ingress.yaml
  target:
    kind: Ingress

generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
- behavior: replace
  literals:
  - database=crud-dev
  - user=devuser
  - password=devpass
  - root-password=devrootpass
  - server=mysql
  name: mysql
  type: Opaque
labels:
- includeSelectors: true
  pairs:
    environment: dev
    sre-team: green
