apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
namespace: dev
commonLabels:
  environment: dev
  sre-team: green

patchesStrategicMerge:
  - namespace.yaml
  - crud-app-replicas.yaml
  - crud-ingress.yaml


generatorOptions:
  disableNameSuffixHash: true


secretGenerator:
- name: mysql
  type: Opaque
  literals:
  - database=crud-dev
  - user=devuser
  - password=devpass
  - root-password=devrootpass
  - server=mysql
