apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  github-eventlistener-ingress
spec:
  rules:
  - host: "crud-webhook.apps.dmi3lab.online"
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: el-github-listener
            port:
              number: 8080
  tls:
  - hosts:
    - crud-webhook.apps.dmi3lab.online
    secretName: crud-webhook-cert